services:

  python:
    container_name: python-container
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "5001:5000" # By default, many Flask applications run on port 5000 (5001 on host to avoid troubles)
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    volumes:
      - ./flask:/usr/src/app
    restart: always

  web:
    container_name: nginx-container
    image: nginx:latest
    ports:
        - "80:7070"
        - "8181:7171"
        - "8282:7272"
    volumes:
        - ./default:/var/www/default
        - ./flowebdev:/var/www/flowebdev
        - ./flask:/var/www/flask
        - ./nginx/nginx.conf:/etc/nginx/nginx.conf
        - ./nginx/flask.conf:/etc/nginx/conf.d/flask.conf
        - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        - ./nginx/logs:/var/log/nginx
    restart: always
